# STAR illesztéshez szükséges indexelés

mkdir ccinerea_AmutBmut_DIR_RRPM
cp -r ./ccinerea_AmutBmut_genome ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARindex
cd ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARindex
STAR --runThreadN 48 --runMode genomeGenerate --genomeDir ../ccinerea_AmutBmut_RRPM_STARindex --sjdbGTFfile ../ccinerea_AmutBmut_RRPM_STARindex/ccinerea_AmutBmut_fixed.gtf --genomeFastaFiles ../ccinerea_AmutBmut_RRPM_STARindex/ccinerea_AmutBmut_genes.fasta --sjdbOverhang 100 --genomeChrBinNbits 12
cd ../..

# STAR illesztés az RRPM-hez  !!!HA AZ SORTOLÁST IS MEG TUDJA CSINÁLNI A STAR!!!

mkdir ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout
cd ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout
STAR --runThreadN 48 --genomeDir ../ccinerea_AmutBmut_RRPM_STARindex --readFilesIn ../../raw_data/CC_H_R2.all.R1.fastq.gz,../../raw_data/CC_H_R3.all.R1.fastq.gz,../../raw_data/CC_H_R4.all.R1.fastq.gz,../../raw_data/CC_VM_R1.all.R1.fastq.gz,../../raw_data/CC_VM_R2.all.R1.fastq.gz,../../raw_data/CC_VM_R3.all.R1.fastq.gz,../../raw_data/CC_P1_R2.all.R1.fastq.gz,../../raw_data/CC_P1_R3.all.R1.fastq.gz,../../raw_data/CC_P1_R4.all.R1.fastq.gz,../../raw_data/CC_P2_R2.all.R1.fastq.gz,../../raw_data/CC_P2_R3.all.R1.fastq.gz,../../raw_data/CC_P2_R4.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R3.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R3.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R3.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R1.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R2.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R3.all.R1.fastq.gz,../../raw_data/CC_FB_T_R1.all.R1.fastq.gz,../../raw_data/CC_FB_T_R2.all.R1.fastq.gz,../../raw_data/CC_FB_T_R3.all.R1.fastq.gz ../../raw_data/CC_H_R2.all.R2.fastq.gz,../../raw_data/CC_H_R3.all.R2.fastq.gz,../../raw_data/CC_H_R4.all.R2.fastq.gz,../../raw_data/CC_VM_R1.all.R2.fastq.gz,../../raw_data/CC_VM_R2.all.R2.fastq.gz,../../raw_data/CC_VM_R3.all.R2.fastq.gz,../../raw_data/CC_P1_R2.all.R2.fastq.gz,../../raw_data/CC_P1_R3.all.R2.fastq.gz,../../raw_data/CC_P1_R4.all.R2.fastq.gz,../../raw_data/CC_P2_R2.all.R2.fastq.gz,../../raw_data/CC_P2_R3.all.R2.fastq.gz,../../raw_data/CC_P2_R4.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R3.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R3.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R3.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R1.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R2.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R3.all.R2.fastq.gz,../../raw_data/CC_FB_T_R1.all.R2.fastq.gz,../../raw_data/CC_FB_T_R2.all.R2.fastq.gz,../../raw_data/CC_FB_T_R3.all.R2.fastq.gz --readFilesCommand zcat --genomeChrBinNbits 12 --outSAMtype BAM SortedByCoordinate --outSAMstrandField intronMotif --twopassMode Basic --outFilterIntronMotifs RemoveNoncanonicalUnannotated --limitBAMsortRAM 80000000000 --alignIntronMax 30000 --alignIntronMin 3
cd ../..

# STAR illesztés az RRPM-hez !!!HA AZ SORTOLÁST NEM TUDJA MEGCSINÁLNI A STAR!!!

mkdir ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout
cd ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout
STAR --runThreadN 48 --genomeDir ../ccinerea_AmutBmut_RRPM_STARindex --readFilesIn ../../raw_data/CC_H_R2.all.R1.fastq.gz,../../raw_data/CC_H_R3.all.R1.fastq.gz,../../raw_data/CC_H_R4.all.R1.fastq.gz,../../raw_data/CC_VM_R1.all.R1.fastq.gz,../../raw_data/CC_VM_R2.all.R1.fastq.gz,../../raw_data/CC_VM_R3.all.R1.fastq.gz,../../raw_data/CC_P1_R2.all.R1.fastq.gz,../../raw_data/CC_P1_R3.all.R1.fastq.gz,../../raw_data/CC_P1_R4.all.R1.fastq.gz,../../raw_data/CC_P2_R2.all.R1.fastq.gz,../../raw_data/CC_P2_R3.all.R1.fastq.gz,../../raw_data/CC_P2_R4.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_K_R3.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_L_R3.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R1.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R2.all.R1.fastq.gz,../../raw_data/CC_YFB_T_R3.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R1.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R2.all.R1.fastq.gz,../../raw_data/CC_FB_KL_R3.all.R1.fastq.gz,../../raw_data/CC_FB_T_R1.all.R1.fastq.gz,../../raw_data/CC_FB_T_R2.all.R1.fastq.gz,../../raw_data/CC_FB_T_R3.all.R1.fastq.gz ../../raw_data/CC_H_R2.all.R2.fastq.gz,../../raw_data/CC_H_R3.all.R2.fastq.gz,../../raw_data/CC_H_R4.all.R2.fastq.gz,../../raw_data/CC_VM_R1.all.R2.fastq.gz,../../raw_data/CC_VM_R2.all.R2.fastq.gz,../../raw_data/CC_VM_R3.all.R2.fastq.gz,../../raw_data/CC_P1_R2.all.R2.fastq.gz,../../raw_data/CC_P1_R3.all.R2.fastq.gz,../../raw_data/CC_P1_R4.all.R2.fastq.gz,../../raw_data/CC_P2_R2.all.R2.fastq.gz,../../raw_data/CC_P2_R3.all.R2.fastq.gz,../../raw_data/CC_P2_R4.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_K_R3.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_L_R3.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R1.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R2.all.R2.fastq.gz,../../raw_data/CC_YFB_T_R3.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R1.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R2.all.R2.fastq.gz,../../raw_data/CC_FB_KL_R3.all.R2.fastq.gz,../../raw_data/CC_FB_T_R1.all.R2.fastq.gz,../../raw_data/CC_FB_T_R2.all.R2.fastq.gz,../../raw_data/CC_FB_T_R3.all.R2.fastq.gz --readFilesCommand zcat --genomeChrBinNbits 12 --outSAMtype BAM Unsorted --outSAMstrandField intronMotif --twopassMode Basic --outFilterIntronMotifs RemoveNoncanonicalUnannotated  --alignIntronMax 30000 --alignIntronMin 3
cd ../..

# a BAM file sortolása !!!HA AZ SORTOLÁST NEM TUDJA MEGCSINÁLNI A STAR!!!

sambamba sort -m 10GB -t 48 -o ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout/Aligned.sortedByCoord.out.bam -p ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout/Aligned.out.bam

# Cufflinks assembly az alternatív splice variánsok meghatározására

cufflinks -p 48 -g ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARindex/ccinerea_AmutBmut_fixed.gtf --max-intron-length 30000 --min-intron-length 3 --overlap-radius 25 --max-bundle-length 250000 -o ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_CUFFout ./ccinerea_AmutBmut_DIR_RRPM/ccinerea_AmutBmut_RRPM_STARout/Aligned.sortedByCoord.out.bam




