# STAR illesztéshez szükséges indexelés

mkdir ltigrinus_DIR_RRPM
cp -r ./ltigrinus_genome ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARindex
cd ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARindex
STAR --runThreadN 16 --runMode genomeGenerate --genomeDir ../ltigrinus_RRPM_STARindex --sjdbGTFfile ../ltigrinus_RRPM_STARindex/ltigrinus_fixed.gtf --genomeFastaFiles ../ltigrinus_RRPM_STARindex/ltigrinus_genes.fasta --sjdbOverhang 100 --genomeChrBinNbits 12
cd ../..

# STAR illesztés az RRPM-hez  !!!HA AZ SORTOLÁST IS MEG TUDJA CSINÁLNI A STAR!!!

mkdir ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout
cd ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout
STAR --runThreadN 16 --genomeDir ../ltigrinus_RRPM_STARindex --readFilesIn ../../raw_data/LT_VM_R1.R1.fastq.gz,../../raw_data/LT_VM_R2.R1.fastq.gz,../../raw_data/LT_VM_R3.all.R1.fastq.gz,../../raw_data/LT_P1_R1.all.R1.fastq.gz,../../raw_data/LT_P1_R2.all.R1.fastq.gz,../../raw_data/LT_P1_R3.all.R1.fastq.gz,../../raw_data/LT_P2_K_R1.all.R1.fastq.gz,../../raw_data/LT_P2_K_R2.all.R1.fastq.gz,../../raw_data/LT_P2_K_R3.all.R1.fastq.gz,../../raw_data/LT_P2_T_R1.all.R1.fastq.gz,../../raw_data/LT_P2_T_R2.all.R1.fastq.gz,../../raw_data/LT_P2_T_R3.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R1.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R2.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R3.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R1.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R2.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R3.all.R1.fastq.gz,../../raw_data/LT_FB_K_R1.all.R1.fastq.gz,../../raw_data/LT_FB_K_R3.all.R1.fastq.gz,../../raw_data/TL_FB_K_R4_R1_001.fastq.gz,../../raw_data/LT_FB_L_R1.R1.fastq.gz,../../raw_data/LT_FB_L_R2.all.R1.fastq.gz,../../raw_data/TL_FB_L_R4_R1_001.fastq.gz,../../raw_data/LT_FB_T_R2.all.R1.fastq.gz,../../raw_data/LT_FB_T_R3.all.R1.fastq.gz,../../raw_data/TL_FB_T_R4_R1_001.fastq.gz ../../raw_data/LT_VM_R1.R2.fastq.gz,../../raw_data/LT_VM_R2.R2.fastq.gz,../../raw_data/LT_VM_R3.all.R2.fastq.gz,../../raw_data/LT_P1_R1.all.R2.fastq.gz,../../raw_data/LT_P1_R2.all.R2.fastq.gz,../../raw_data/LT_P1_R3.all.R2.fastq.gz,../../raw_data/LT_P2_K_R1.all.R2.fastq.gz,../../raw_data/LT_P2_K_R2.all.R2.fastq.gz,../../raw_data/LT_P2_K_R3.all.R2.fastq.gz,../../raw_data/LT_P2_T_R1.all.R2.fastq.gz,../../raw_data/LT_P2_T_R2.all.R2.fastq.gz,../../raw_data/LT_P2_T_R3.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R1.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R2.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R3.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R1.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R2.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R3.all.R2.fastq.gz,../../raw_data/LT_FB_K_R1.all.R2.fastq.gz,../../raw_data/LT_FB_K_R3.all.R2.fastq.gz,../../raw_data/TL_FB_K_R4_R2_001.fastq.gz,../../raw_data/LT_FB_L_R1.R2.fastq.gz,../../raw_data/LT_FB_L_R2.all.R2.fastq.gz,../../raw_data/TL_FB_L_R4_R2_001.fastq.gz,../../raw_data/LT_FB_T_R2.all.R2.fastq.gz,../../raw_data/LT_FB_T_R3.all.R2.fastq.gz,../../raw_data/TL_FB_T_R4_R2_001.fastq.gz --readFilesCommand zcat --genomeChrBinNbits 12 --outSAMtype BAM SortedByCoordinate --outSAMstrandField intronMotif --twopassMode Basic --outFilterIntronMotifs RemoveNoncanonicalUnannotated --limitBAMsortRAM 80000000000 --alignIntronMax 30000 --alignIntronMin 3
cd ../..

# STAR illesztés az RRPM-hez !!!HA AZ SORTOLÁST NEM TUDJA MEGCSINÁLNI A STAR!!!

mkdir ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout
cd ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout
STAR --runThreadN 16 --genomeDir ../ltigrinus_RRPM_STARindex --readFilesIn ../../raw_data/LT_VM_R1.R1.fastq.gz,../../raw_data/LT_VM_R2.R1.fastq.gz,../../raw_data/LT_VM_R3.all.R1.fastq.gz,../../raw_data/LT_P1_R1.all.R1.fastq.gz,../../raw_data/LT_P1_R2.all.R1.fastq.gz,../../raw_data/LT_P1_R3.all.R1.fastq.gz,../../raw_data/LT_P2_K_R1.all.R1.fastq.gz,../../raw_data/LT_P2_K_R2.all.R1.fastq.gz,../../raw_data/LT_P2_K_R3.all.R1.fastq.gz,../../raw_data/LT_P2_T_R1.all.R1.fastq.gz,../../raw_data/LT_P2_T_R2.all.R1.fastq.gz,../../raw_data/LT_P2_T_R3.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R1.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R2.all.R1.fastq.gz,../../raw_data/LT_YFB_K_R3.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R1.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R2.all.R1.fastq.gz,../../raw_data/LT_YFB_T_R3.all.R1.fastq.gz,../../raw_data/LT_FB_K_R1.all.R1.fastq.gz,../../raw_data/LT_FB_K_R3.all.R1.fastq.gz,../../raw_data/TL_FB_K_R4_R1_001.fastq.gz,../../raw_data/LT_FB_L_R1.R1.fastq.gz,../../raw_data/LT_FB_L_R2.all.R1.fastq.gz,../../raw_data/TL_FB_L_R4_R1_001.fastq.gz,../../raw_data/LT_FB_T_R2.all.R1.fastq.gz,../../raw_data/LT_FB_T_R3.all.R1.fastq.gz,../../raw_data/TL_FB_T_R4_R1_001.fastq.gz ../../raw_data/LT_VM_R1.R2.fastq.gz,../../raw_data/LT_VM_R2.R2.fastq.gz,../../raw_data/LT_VM_R3.all.R2.fastq.gz,../../raw_data/LT_P1_R1.all.R2.fastq.gz,../../raw_data/LT_P1_R2.all.R2.fastq.gz,../../raw_data/LT_P1_R3.all.R2.fastq.gz,../../raw_data/LT_P2_K_R1.all.R2.fastq.gz,../../raw_data/LT_P2_K_R2.all.R2.fastq.gz,../../raw_data/LT_P2_K_R3.all.R2.fastq.gz,../../raw_data/LT_P2_T_R1.all.R2.fastq.gz,../../raw_data/LT_P2_T_R2.all.R2.fastq.gz,../../raw_data/LT_P2_T_R3.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R1.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R2.all.R2.fastq.gz,../../raw_data/LT_YFB_K_R3.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R1.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R2.all.R2.fastq.gz,../../raw_data/LT_YFB_T_R3.all.R2.fastq.gz,../../raw_data/LT_FB_K_R1.all.R2.fastq.gz,../../raw_data/LT_FB_K_R3.all.R2.fastq.gz,../../raw_data/TL_FB_K_R4_R2_001.fastq.gz,../../raw_data/LT_FB_L_R1.R2.fastq.gz,../../raw_data/LT_FB_L_R2.all.R2.fastq.gz,../../raw_data/TL_FB_L_R4_R2_001.fastq.gz,../../raw_data/LT_FB_T_R2.all.R2.fastq.gz,../../raw_data/LT_FB_T_R3.all.R2.fastq.gz,../../raw_data/TL_FB_T_R4_R2_001.fastq.gz --readFilesCommand zcat --genomeChrBinNbits 12 --outSAMtype BAM Unsorted --outSAMstrandField intronMotif --twopassMode Basic --outFilterIntronMotifs RemoveNoncanonicalUnannotated  --alignIntronMax 30000 --alignIntronMin 3
cd ../..

# a BAM file sortolása !!!HA AZ SORTOLÁST NEM TUDJA MEGCSINÁLNI A STAR!!!

sambamba sort -m 10GB -t 16 -o ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout/Aligned.sortedByCoord.out.bam -p ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout/Aligned.out.bam

# Cufflinks assembly az alternatív splice variánsok meghatározására

cufflinks -p 16 -g ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARindex/ltigrinus_fixed.gtf --max-intron-length 30000 --min-intron-length 3 --overlap-radius 25 --max-bundle-length 250000 -o ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_CUFFout ./ltigrinus_DIR_RRPM/ltigrinus_RRPM_STARout/Aligned.sortedByCoord.out.bam